config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/about', to: 'pages#about'
  get '/help', to: 'pages#help'

  resources :todos
end

app/models/Todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      flash[:notice] = "Todo was Successfully created"
      redirect_to todo_path(@todo)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @todo.update(todo_params)
      flash[:notice] = "Todo was succsessfully updated"
      redirect_to todo_path(@todo)
    else
      render 'edit'
    end
  end

  def destroy
    @todo.destroy
    flash[:notice] = "Todo was successfully deleted"
    redirect_to todos_path
  end

  private

  def set_todo
     @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <ul>
    <li id="msg_success"><%= msg %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="my_jquery_functions.js"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Hello again</h1>

<%= link_to 'Home', root_path %>

app/views/pages/help.html.erb
<h1>Help Page</h1>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<h1>Hello World!</h1>

<%= link_to 'About', about_path %> |
<%= link_to 'Help', help_path %> |
<%= link_to 'All Todos', todos_path %> |
<%= link_to 'Add A Todo', new_todo_path %>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
  <h2>The following errors prevented the todo from being saved</h2>
  <ul>
    <% @todo.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @todo do |f|  %>
  <p>
    <%= f.label :name %> <br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %> <br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "All Todos", todos_path %> |
<%= link_to "Home", root_path %>

app/views/todos/edit.html.erb
<h1>Edit Todo</h1>

<%= render 'todos/form' %>

app/views/todos/index.html.erb
<h1>You have <%= @todos.count %> Todos</h1>
<p><%= link_to 'Add A Todo', new_todo_path %></p>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>

  <% @todos.each_with_index do |todo, index| %>
    <tr>
      <td> <%= link_to "#{index + 1} #{todo.name.capitalize}", todo_path(todo.id) %></td>
      <td> <%= "#{todo.description.capitalize}" %></td>
      <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
      <td><%= link_to "Delete", todo_path(todo), method: :delete, data:{confirm: "Are you sure"} %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to 'Home', root_path %></p>

app/views/todos/new.html.erb
<h1>Hello new page</h1>

<%= render 'todos/form' %>

app/views/todos/show.html.erb
<h1>Showing a todo</h1>

<p>
  Name: <%= @todo.name.capitalize %>
</p>
<p>
  Description: <%= @todo.description.capitalize  %>
</p>

<p>

  <%= link_to 'Home', root_path %> |
  <%= link_to 'All Todos', todos_path %>
</p>